# Generated by Django 3.1.7 on 2021-03-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciepe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciepe_name', models.CharField(max_length=100)),
                ('ingridiants', models.TextField()),
                ('process', models.TextField()),
                ('images', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
